apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.app }}
