name: Build with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building java here"

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run: sh ./docker-build-and-push.sh