name: Build with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      run: echo "building java here"
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn clean install -DskipTests

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo $(docker --version)